### ISSUE TITLE
When i use the Datelist it show  "Maximum call stack size exceeded."

### ISSUE THREAD

**Issue by CraftLCL** [NonFactors/MVC5.Datalist#11]
error:

jquery.js:6059 GET data:image/gif;base64,R0lGODlhEAAQAPMPAJycnBQUFODg4L6+vnp6egAAAFhYWDY2NoqKivDw8CQkJGhoaEZGRqysrAQEBP///yH/C05FVFNDQVBFMi4wAwEAAAAh+QQFCgAPACwAAAAAEAAQAAAEcfDJl+gydeonlEhFIVCbJBRK4ojJqAkjUiArnEkJM4OOYXymjEDnGLhwQFyicTjiNAiGD1CiJK5RBoNaul6tA8ItqEkgAgxnyzghKABmBEzQoLA5I8Fh0AAI5KM2TCQYEDwBUAnAlAgQjhxIDYyUDA1URACH5BAUKAA8ALAAAAAAPABAAAARd8Mn5yJKJTiaVFEGjSUeiOIJSDKMEKAFQcJMRJ8FhFUWWSYbCQTAZEFu01qOxIBBYygfAsFhAox/A6DdpMAxbwQ/BaCQADYH6KNYsBAPzVUPQxiVzDCBzfxyVaiMRACH5BAUKAA8ALAAAAAAQAA8AAARa8Mn5AKJYLslUSkcmOUbSJYaYVEXTNZMwSMTRgAyCHIWAFD1NIBUDAAuzyWCxUhYukoEOIMh8rg2CVsR9wLqUBaLZBRAGiQH6qpIgBPCEgIwBzOAPOfeLz1MiACH5BAUKAA8ALAAAAAAQABAAAARc8MkpAb2SpGeYNAP2HATnLdgmBUMXookgIYvMEADgJVagEqSH6jFQiB4liqyW2AAaDdEiEHCAcgDZZVHoHiihi2AsUAkQluNkkH2M1UJJYtAcHgeyJtwtt8P1GBEAIfkEBQoACAAsAAAAABAADgAABEUQyYkIoVgaWQrP3NYhASgRXgeQmBEMSHFYXhVPRrFh9UrtmMNEgAD4gp1CyXLJlD5DzECWOU6mHSJCa0pmuJQBUAIGRQAAIfkEBQoADgAsAAAAABAAEAAABGvQyenGoNilJhGRhJAlBIcgDqKImbAIpxCg1NCICGARR6UwksQAMUhMEgKD48CSCDiUBANg1AiuVQrAYGAgrtgMQKEILKIYwQGAQTYdTwkwKDAmqoFC0hHIZhoFSg5QaBMKBRcjaQVsGY5+EQAh+QQFCgAPACwAAAAAEAAQAAAEW/DJ+YSgWA4JAM/c1XgAA0pIMj5Mg1nJ0wwWsEjMLQl0tgQGTOKCWbgmiSSosVgEk8pMg3E4EE4TQyOK3TwWMRBhoXgkbodToIB4XHmgxJpIjDsKF8cxbjiEKREAIfkEBQoADgAsAQABAA8ADwAABFbQSSHHkE3qWu9Y2+Zdy+UkpyZQTkM4goFIiYCGxPFu94aYoeCAQMwENR+D7EgrBWusmsKx2xQKCARjOmP4CgSFAuCYhQRXSiBxODYKl8DaoQCqNIZjBAAh+QQFCgAPACwAAAAAEAAQAAAEXfDJ+VKiWN4nhBwbJlwdB4RU4nUJ4mGbZQ2NhAAZDCx4jgEvH0WAKAonAoKy9lEMMK4ho1DoTRgBhMZROHgUgMaC8QAoFhLA03Y41HrBiSLRfhgcPsf3ICHnNko5EQAh+QQFCgAOACwAAAEAEAAPAAAEWtDJ6VKSgmpp5dha922ZJpTACE4NMlxUSanOEtwL2OzDUfwMEADgSpwAAZkEsHK8JonFgSlR1BIKRsOBMDgNBElDBjAwBoEtTHNwmB2E9mZgdTCCNeUGgQBFAAAh+QQFCgAPACwAAAEAEAAPAAAEWPDJSV+qeCZRBcfCRRUFUonJ8A1k8U2CWhFF04mSomfP4AsGRyBAyPgan0SDgbFVDJKXBLFwPg6PIsPgAywkBIBkIBE3CAsBlhdgoh8AJki+gCaKvLIYEwEAIfkEBQoADwAsAAABAA8ADwAABFrwyRGEvPiOorKXRtF8UvcIReEJyWkC45WwGOAMWSshB8MgnplAQFAYgbmhpTUweHAywiPgaSCgTuCCMGwATrDTJDBASBeWh059WDzMjwZhfXG/pY8vKR7DRAAAOw== net::ERR_INVALID_URL
curCSS @ jquery.js:6059
css @ jquery.js:6385
getWidthOrHeight @ jquery.js:6214
(anonymous) @ jquery.js:6419
swap @ jquery.js:4435
get @ jquery.js:6418
css @ jquery.js:6380
(anonymous) @ jquery.js:9986
access @ jquery.js:3943
jQuery.fn.(anonymous function) @ jquery.js:9959
_size @ jquery-ui.js:12439
(anonymous) @ jquery-ui.js:144
open @ jquery-ui.js:11926
(anonymous) @ jquery-ui.js:144
(anonymous) @ jquery-ui.js:250
each @ jquery.js:368
each @ jquery.js:157
$.fn.(anonymous function) @ jquery-ui.js:230
(anonymous) @ mvc-datalist.js:134
setTimeout (async)
click @ mvc-datalist.js:133
handlerProxy @ jquery-ui.js:586
dispatch @ jquery.js:5110
elemData.handle @ jquery.js:4918
jquery.js:5226 Uncaught RangeError: Maximum call stack size exceeded.

**Comment by Muchiachio** [comment]
Seems like a jquery bug, could you share a small repro?
So we can possibly fix it or send it to jquery issue tracker accordingly.

**Comment by CraftLCL** [comment]
it happened when i use the grid in iframe .

**Comment by Muchiachio** [comment]
Could you share a repro? I tried using it in an iframe and it worked properly.
Do you have a lot of columns and the dialog goes off screen?
