### ISSUE TITLE
Datalist inside Bootsrap Modal

### ISSUE THREAD

**Issue by junrikson** [NonFactors/MVC5.Datalist#13]
Hi there, 

I am using this Data List Look up inside Modal like below : 
![image](https://user-images.githubusercontent.com/5647735/44697687-0716df80-aaa7-11e8-83d1-60ccc44e5965.png)

I modified some z-index in `mvc-datalist.css` (+2000) so the Data List become on top of my bootstrap modal. Everything is ok except the Search Input, the cursor become disabled. I tried to look into some css/js what caused this problem and I can't find any clue. 

Could you give me a possibility caused by this problem so I can try to look into. 

Thank you.

**Comment by junrikson** [comment]
Hi there, 

Here a sample for this issue. I modify z-index (+2000) in `mvc-datalist.css`

[sample.zip](https://github.com/NonFactors/MVC5.Datalist/files/2328275/sample.zip)

Thank you.

**Comment by Muchiachio** [comment]
It's bootstrap preventing the focus on modals with `tabindex="-1"`.

**Comment by junrikson** [comment]
Owh ok. Thank you.
