### ISSUE TITLE
Filter for multiple value

### ISSUE THREAD

**Issue by junrikson** [NonFactors/MVC5.Datalist#14]
Hi there,

How I can filter a field by some value? For example `Unit == 'A' || Unit == 'B' || Unit == 'C'`
I tried with :
`datalist.FilterBySearch(db.Units.Where(x => x == "A" || x == "B" || x == "C"));`

But it doesn't works.

**Comment by Muchiachio** [comment]
It already does a case insensitive contains search on all the string fields automatically.
Is it not working?

**Comment by junrikson** [comment]
I'm not quite sure how to do that. Actually it is an enum. 

I have tried so many things like making virtual field in model for this search but it doesn't work and return error that linq (Iqueryable) just work with mapping field.

Also I have tried with 
```
            filter.AdditionalFilters["MasterPriceUnit.Unit"] = EnumBasicPrice.A;
            filter.AdditionalFilters["MasterPriceUnit.Unit"] = EnumBasicPrice.B;
            filter.AdditionalFilters["MasterPriceUnit.Unit"] = EnumBasicPrice.C;
```
 But it is just return the first filter, which A.

**Comment by Muchiachio** [comment]
Additional filter does that but it uses `&&` operator and doesn't include enums, your best bet would be
```C#
public override IQueryable<TView> FilterByAdditionalFilters(IQueryable<TView> models)
{
    return models.Where(...); // using values from Filter.AdditionalFilters
}
```
however if it's not an a filter specified by the user, you should filter the data in `GetModels` method instead.

**Comment by junrikson** [comment]
Thank you alot. I just know I can override FilterByAdditionalFilters :D
