### ISSUE TITLE
Can I use MVC5.Datalist  in partial view 

### ISSUE THREAD

**Issue by rushikeshraut** [NonFactors/MVC5.Datalist#15]
I tried in partial view but giving error does not contain definition for DataListFor and no accessible method for data list

**Comment by Muchiachio** [comment]
Try including `@using Datalist;` by hand in your partial view.

**Comment by rushikeshraut** [comment]
Not working

Partial view code
@Html.DatalistFor(model => model.DesignationId, new DesignationDatalist { Url = "GetDesignation" })

designationList Class

public class DesignationDatalist : MvcDatalist<tblDesignationM>
    {
        
        public DesignationDatalist()
        {
            Url = "GetDesignation";
            Title = "Get Designation";

            Filter.Sort = "AccessLevel";
            Filter.Order = DatalistSortOrder.Desc;
        }

        public override IQueryable<tblDesignationM> GetModels()
        {
            DBHelper db = new DBHelper(false);
            return tblDesignationM.RetrieveAll(db).AsQueryable();
        }
    }

controller method
[HttpGet]
        public JsonResult GetDesignation(DatalistFilter filter, Boolean? isWorking)
        {
            DesignationDatalist datalist = new DesignationDatalist() { Filter = filter };
            return Json(datalist.GetData(), JsonRequestBehavior.AllowGet);
        }

but not binding data to datalist

**Comment by Muchiachio** [comment]
So you are still getting `DataListFor and no accessible` or something else?

**Comment by rushikeshraut** [comment]
data not bind to datalist

**Comment by Muchiachio** [comment]
Did you initialize the datalist with js call?

**Comment by rushikeshraut** [comment]
I initialize it as follow in my layout page
 <script>
        [].forEach.call(document.getElementsByClassName('datalist'), function (element) {
            new MvcDatalist(element);
        });
    </script>

**Comment by Muchiachio** [comment]
If you render your partial after this call, or refresh it using ajax, you need to call it again, if it still doesn't work, when the only way is to debug this call and check why it's not bound.

**Comment by rushikeshraut** [comment]
it working now when I initialize it when partial view renders,but it  bind id not name

**Comment by Muchiachio** [comment]
Can you provide a small repro project on github?
