### ISSUE TITLE
Bug in mvc-datalist.js

### ISSUE THREAD

**Issue by atkulp** [NonFactors/MVC5.Datalist#18]
Looks like a typo where the word "this" got mixed with "autocomplete".  I'd do a PR for the fix, but I can't right now.  If you aren't able to get to it in the next few days I might help out.

![image](https://user-images.githubusercontent.com/3195410/65820915-0cf16e00-e22f-11e9-903c-fcdebfe0fd4a.png)

https://github.com/NonFactors/MVC5.Datalist/blob/a2eee43b3da30e459528edc21fd786aca52a4e71/src/Datalist/Scripts/MvcDatalist/mvc-datalist.js#L493

**Comment by Muchiachio** [comment]
Wow... and it's so old, it's ok I will fix it.

**Comment by atkulp** [comment]
Awesome!  Thanks!
