### ISSUE TITLE
Working Sample.

### ISSUE THREAD

**Issue by cgoss** [NonFactors/MVC5.Datalist#6]
Can you create a working sample for this project. 
Would you be able to make the test site available in github?

**Comment by Muchiachio** [comment]
Official documentation [page source](https://github.com/NonFactors/MVC5.Datalist.Web), has various examples. You can also check out [MVC.Template](https://github.com/NonFactors/MVC5.Template/blob/develop/src/MvcTemplate.Controllers/Datalist/DatalistController.cs) example for actual database usage.

**Comment by cgoss** [comment]
The problem I am having is that the dialog is not being displayed, everything else is firing as expected and data is being supplied.

I'll have to give it another try tonight, if there are any suggestions you may have on where to look i would appreciate it. 

Thanks

**Comment by Muchiachio** [comment]
Here are few things to check, maybe it will help
- If you included jquery ui scripts.
- If there are no js errors in the console.
- If you rendered `MvcDatalist/_Dialog` partial to your page.

**Comment by cgoss** [comment]
Is there a specific version of jquery-ui that its dependant on? Or is it
pulled from nuget?

**Comment by Muchiachio** [comment]
It has some early working version in the nuget dependencies.
But most of the versions should work as long as they include dialog widgets.

**Comment by cgoss** [comment]
The partial _Dialog is being added to the page. Does that have to be via
Html.Render method or via Html.Partial?

I will build a stand alone sample tonight to try, I'm thinkng that maybe I
have some css conflict that is causing the dialog to display in the
background or something.

Thanks for your help.

**Comment by Muchiachio** [comment]
It's a partial, these [installation steps](http://mvc-datalist.azurewebsites.net/Home/Installation) should be enough to get you started.

**Comment by cgoss** [comment]
I am still getting the same problem, below is the example project I have created and I have used the About Page and Home Controller to host the code. If you could let me know what I've done wrong I'd appreciate it. 

https://github.com/cgoss/DataListTest/

One thing to note is that I'm not using an ORM or context to retrieve the data, they will be just POCO classes for the moment. On a quick inspection I don't get any rows back from the GetData() function.

**Comment by cgoss** [comment]
I copied over the entire contents of Content and Scripts and used your bundle config from your sample project and it now works. 

So there is some conflict in one of those areas that is preventing the dialog from showing up. I will let you know when I locate the source of the problem.

**Comment by Muchiachio** [comment]
Ok, I started looking at your project, but I will wait now.

**Comment by cgoss** [comment]
It looks like it may have been either an scripting order issue.

I started off with building the bundles differently, as per the default mvc project. The way you have it is definitely easier to read. 

The other major change is how and where the bundles were rendered to the _Layout.cshtml page. 
Once that was done they worked, commenting out one by one it turned out to be the jquery-ui that produced the symptom I was seeing. So I suspect that it was the order in which I had the scripts rendered on the layout page. 

This can be marked as resolved.
