### ISSUE TITLE
allow the @Value attribute so we can set default value or use in Edit pages before search 

### ISSUE THREAD

**Issue by aliramadan8** [NonFactors/MVC5.Datalist#7]
Just to allow the value to be used so we can use it to show default value or in edit mode to show already existing value instead of using extra controls.

`@Html.Datalist("MemberId", new MembersDatalist(), new { @class = "form-control ", value = "hi" })`

**Comment by Muchiachio** [comment]
You can already do that, check `@Html.Datalist("MemberId", ...)` parameters, one of them is a value.

**Comment by aliramadan8** [comment]
thanks for your rapid response ,i did that
@Html.Datalist("ddlMemberID", new clMembersDataDatalist(),"HI",new { @class = "form-control " })
but it showed a background control as below 
![image](https://cloud.githubusercontent.com/assets/24622815/25334010/76d1647e-28f5-11e7-91d8-24ddd25a9b68.png)

**Comment by Muchiachio** [comment]
I think you are misunderstanding what the value does in the datalist.
If you set it to `"HI"`, it means that datalist will try to load the value with an id `"HI"` and set it's autocomplete value to the visible input. You can check the html around datalist input and you will see it as hidden input.

If you still want to set `"HI"` as an initial datalist search value, you will have to use javascript for that.

**Comment by aliramadan8** [comment]
amazing , i did misunderstood the concept ,thanks for your support , done
