### ISSUE TITLE
Invalid DatalistUrl for longer pages 

### ISSUE THREAD

**Issue by aliramadan8** [NonFactors/MVC5.Datalist#8]
Hi , while i use different pages to get the datalist , for normal pages with no parameter it works fine 
http://localhost:23588/acPlayGroundSchedule/Create 
it work like charm 
![image](https://cloud.githubusercontent.com/assets/24622815/25378625/45200f66-29b3-11e7-9c3c-c7c05ccd7c18.png)
while for the URL
 http://localhost:23588/acPlayGroundSchedule/Create/2000
it do not work , and when i inspect the send URL i found it as below 
http://localhost:23588/acPlayGroundSchedule/create/AllacTrainers?search=&sort=Name&order=Asc&rows=5&page=0&_=1493066992185  
while it should have been as below 
http://localhost:23588/acPlayGroundSchedule/AllacTrainers?search=&sort=Name&order=Asc&rows=5&page=0&_=1493066992185
with exact Error below :
GET http://localhost:23588/acPlayGroundSchedule/create/AllacTrainers?search=&sort=Name&order=Asc&rows=5&page=0&_=1493066992185 500 (Internal Server Error)
![image](https://cloud.githubusercontent.com/assets/24622815/25378941/1abdd0f4-29b4-11e7-9301-f632a489601e.png)

it seems that the URL only excluded last part of the original URL and then added its data-url 

When i changed the URL to be as below it worked again fine 
http://localhost:23588/acPlayGroundSchedule/Create?ID=2333

although the first one is the common for MVC 

any solution for that ???

**Comment by Muchiachio** [comment]
Datalist works through ajax, so if you set datalist url to `AllacTrainers` it will use an ajax call with that url.
By default, ajax tries to make a relative url with `AllacTrainers`, unless you use `/AllacTrainers`, meaning start url from the page root.

My recommendation is to always use full url, so that ajax doesn't try to use it as a relative path to action.

**Comment by aliramadan8** [comment]
again , perfect , thanks for the amazing control , it saved em thousands of hours , thanks
