### ISSUE TITLE
Id Property

### ISSUE THREAD

**Issue by cxs-mahendra** [NonFactors/MVC5.Datalist#9]
Hi,

I have my entity Id property as 'long'

public class Person
    {
        [DatalistColumn(Hidden = true)]
        public long Id { get; set; }
........
.........

CSHTML Code
****************
@Html.Datalist("Datalist", new PeopleDatalist { Url = "/Home/AllPeople" }, "10000000000000002")

Controller Code
*****************
public JsonResult AllPeople(DatalistFilter filter)
        {
            return Json(new PeopleDatalist { Filter = filter }.GetData(), JsonRequestBehavior.AllowGet);

        }

In the controller code, it throws following error 

"Datalist.DatalistException: ''Person.Id' property type has to be a string or an int.'

Can you please provide me some workaround for the above error.
You can reply me at mahendra.jha@citixsys.com

Regards,
Mahendra

**Comment by Muchiachio** [comment]
Override `FilterByIds` and `FilterByNotIds` to filter long values.

**Comment by cxs-mahendra** [comment]
Any Plan to upgrade the Datalist on .Net Core
